Extension placeholders: Allow extension to expose an 'error_message' function
Idea is that extension developers can signal that a given extension on a given platform & version has
not been built on purpose.
Example can be informing users that platform is not supported (yet) or that a given DuckDB version is not served.

Note that error_message function is NOT prefixed by extension name, so the same placeholder can be used to cover a wide
range of DuckDB versions or extensions.
Error message can be arbitrary.

Example of intended use:
% ./build/release/duckdb -unsigned
v0.8.2-dev4022 c4cff1d8b8
Enter ".help" for usage hints.
D LOAD 'path/to/some.duckdb_extension';
Error: Invalid Input Error: Extension "path/to/some.duckdb_extension" exposes an error_message function
Self-reported error message: "This is a placeholder DuckDB extension"